name: Build Release

on:
  push:
    branches: [ '*', '!master' ]

jobs:

  app_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install protobuf
        run: sudo apt-get install -y lld jq protobuf-compiler
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bins --release